apiVersion: v1
kind: Service
metadata:
  name: ussd-service
  labels:
    app.kubernetes.io/name: ussd-service
spec:
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ussd-service
