apiVersion: v1
kind: Service
metadata:
  name: trading-service
  labels:
    app.kubernetes.io/name: trading-service
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trading-service
