apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  labels:
    app.kubernetes.io/name: market-data-service
spec:
  type: ClusterIP
  ports:
    - port: 8007
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: market-data-service
